"""Small helpers for producing consistent booktabs-style LaTeX tables."""

from __future__ import annotations
from pathlib import Path


def fmt_int(n: int | None) -> str:
    """Format an integer with thousand separators; '--' for None."""
    return "--" if n is None else f"{int(n):,}"


def fmt_float(x: float | None, digits: int = 2) -> str:
    """Format a float with given decimal places; '--' for None."""
    return "--" if x is None else f"{x:.{digits}f}"


def fmt_pct(x: float | None, digits: int = 2) -> str:
    """Format a value as a percent (already scaled 0-100) with given decimals."""
    return "--" if x is None else f"{x:.{digits}f}"


def write_latex_table(
    path: Path,
    caption: str,
    label: str,
    column_spec: str,
    header_row: list[str],
    body_rows: list[list[str]],
    section_headers: dict[int, str] | None = None,
    notes: list[str] | None = None,
    width: str = "\\columnwidth",
) -> None:
    """Write a small booktabs-style table to `path`.

    Args:
        path: Output .tex file path
        caption: Table caption text
        label: LaTeX label (e.g. "tab:dataset_stats")
        column_spec: LaTeX tabular column spec (e.g. "lrrrrr")
        header_row: List of header cell strings (first row)
        body_rows: List of rows, each a list of cell strings
        section_headers: Optional dict mapping row index -> section header text.
            A \\midrule and \\multicolumn heading are inserted BEFORE that row.
        notes: Optional list of footnote strings (rendered as tablenotes)
        width: tabular* width (default \\columnwidth)
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    section_headers = section_headers or {}
    notes = notes or []

    lines: list[str] = []
    lines.append("% Auto-generated by analysis/paper_figures/  — do not edit by hand")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append(f"  \\caption{{{caption}}}")
    lines.append(f"  \\label{{{label}}}")
    if notes:
        lines.append("  \\begin{threeparttable}")
    lines.append("  \\small\\setlength{\\tabcolsep}{5pt}")
    lines.append(f"\\begin{{tabular*}}{{{width}}}{{{column_spec[0]}@{{\\extracolsep{{\\fill}}}}{column_spec[1:]}}}")
    lines.append("  \\toprule")
    lines.append("  " + " & ".join(header_row) + " \\\\")
    lines.append("  \\midrule")

    ncols = len(header_row)
    first_section = True
    for idx, row in enumerate(body_rows):
        if idx in section_headers:
            # Separate each section with a midrule (except before the first one,
            # which already has one after the header row).
            if not first_section:
                lines.append("  \\midrule")
            first_section = False
            lines.append(f"  \\multicolumn{{{ncols}}}{{l}}{{\\textit{{{section_headers[idx]}}}}} \\\\")
            lines.append("  \\midrule")
        lines.append("  " + " & ".join(row) + " \\\\")

    lines.append("  \\bottomrule")
    lines.append("\\end{tabular*}")
    if notes:
        lines.append("  \\begin{tablenotes}")
        lines.append("    \\footnotesize")
        for n in notes:
            lines.append(f"    \\item {n}")
        lines.append("  \\end{tablenotes}")
        lines.append("  \\end{threeparttable}")
    lines.append("\\end{table}")

    path.write_text("\n".join(lines) + "\n")
