#!/usr/bin/env bash
# =============================================================================
# StayRTR Setup Script
# =============================================================================
# Installs Go (if needed) and StayRTR for RPKI validation.
#
# Usage: bash scripts/setup_stayrtr.sh
# =============================================================================

set -euo pipefail

STAYRTR_DIR="$(cd "$(dirname "$0")/.." && pwd)/stayrtr"

echo "=== StayRTR Setup ==="

# Check for Go
if ! command -v go &> /dev/null; then
    echo "Go is not installed. Please install Go 1.21+ first:"
    echo "  https://go.dev/doc/install"
    echo ""
    echo "On Ubuntu/Debian:"
    echo "  sudo apt-get install golang-go"
    echo ""
    echo "On macOS:"
    echo "  brew install go"
    exit 1
fi

echo "Go version: $(go version)"

# Install StayRTR
echo ""
echo "Installing StayRTR..."
go install github.com/bgp/stayrtr/cmd/stayrtr@latest

if command -v stayrtr &> /dev/null; then
    echo "StayRTR installed successfully: $(which stayrtr)"
else
    GOPATH="${GOPATH:-$HOME/go}"
    if [ -f "$GOPATH/bin/stayrtr" ]; then
        echo "StayRTR installed at: $GOPATH/bin/stayrtr"
        echo "Add to PATH: export PATH=\$PATH:$GOPATH/bin"
    else
        echo "Warning: stayrtr binary not found in PATH or GOPATH"
    fi
fi

# Create directory structure
mkdir -p "$STAYRTR_DIR/cache"
echo ""
echo "Created directory: $STAYRTR_DIR"
echo "  cache/              - RTR cache data"
echo "  vrp_generated.json  - Generated by scripts/generate_vrp.py"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Generate VRP from dataset:"
echo "     python3 scripts/generate_vrp.py dataset/caida_100 stayrtr/vrp_generated.json"
echo ""
echo "  2. (Optional) Run StayRTR daemon:"
echo "     stayrtr -bind :8282 -json.path stayrtr/vrp_generated.json"
